# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
import itertools
import os 
import glob
import sys
import pandas as pd

configfile: "../config/config.yaml"
include: "rules/common.smk"
include: "rules/metagenomics.smk"
localrules: multiqc_trimmed

rule all:
    input:
        expand("../results/{dataset}/filtered/{sample}.filtered.R1.fastq.gz",
            zip, sample=samples["sample"], dataset=samples["dataset"]), #  FastP R2
        expand("../results/{dataset}/filtered/{sample}.filtered.R2.fastq.gz", 
            zip, sample=samples["sample"], dataset=samples["dataset"]), #  FastP R2
        expand("../results/{dataset}/filtered/fastqc/{sample}.filtered.R1_fastqc.html",
            zip, sample=samples["sample"], dataset=samples["dataset"]), #  FastQC
        expand("../results/{dataset}/bwa/{sample}.mapped.bam",
            zip, sample=samples["sample"], dataset=samples["dataset"]), #  BWA
        expand("../results/{dataset}/bwa/{sample}.unmapped.bam",
            zip, sample=samples["sample"], dataset=samples["dataset"]),  # BWA Unmapped
        expand("../results/{dataset}/bwa/{sample}.clean.R1.fastq",
            zip, sample=samples["sample"], dataset=samples["dataset"]), #  BWA fastq R1
        expand("../results/{dataset}/bwa/{sample}.clean.R2.fastq",
            zip, sample=samples["sample"], dataset=samples["dataset"]), #  BWA fastq R2
        directory("../resources/metaphlan_db"), #  Metaphlan setup/Database
        expand("../results/{dataset}/abundance/metaphlan/{sample}.metaphlan_profile.txt",
            zip, sample=samples["sample"], dataset=samples["dataset"]), # Metaphlan profiles
        "../results/allDatasets/metaphlan/merged_abundance_table.allDatasets.txt", #  Metaphlan merged abundance table
        "../results/allDatasets/metaphlan/merged_abundance_table.species.allDatasets.txt", #  Metaphlan species abundance table
        "../results/allDatasets/metaphlan/merged_abundance_table.genus.allDatasets.txt", #  " " genus
        "../results/allDatasets/metaphlan/abundance_heatmap_species.allDatasets.png",
        "../results/allDatasets/coassembly/concat_reads/concat_reads.clean.R1.fastq", # Concat R1
        "../results/allDatasets/coassembly/concat_reads/concat_reads.clean.R2.fastq", # Concat R2
        "../results/allDatasets/coassembly/megahit_result/final.contigs.fa", #  megahit coassembly
        "../results/allDatasets/coassembly/quast/report.html"