---
title: "NonPareil Diversity Anlaysis"
output: html_notebook
---


```{r}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(cowplot)
library(Nonpareil)
```


# Get list of NonPareil outputs
```{r}
np_list <- list.files(path = "../../results/nonpareil_out", pattern='*\\.npo', recursive=TRUE, full.names=TRUE)
np_list<-np_list[grep("B1|B2", np_list)]
np_length <- length(np_list)
```

# Graph NonPareil Curves
```{r}
#pdf(file="../../results/notebook_out/00_NonPareilPlot.pdf")
Nonpareil.legend(Nonpareil.curve.batch(np_list, 
                                       plot.opts = list(legend = NA, 
                                                        plot.model = F, 
                                                        plot.diversity = F,
                                                        main = NA)), cex = 0.90)
Nonpareil.curve.batch(np_list, plot.opts = list(legend = NA, 
                                                        plot.model = F, 
                                                        plot.diversity = F,
                                                        main = NA))
np_list_pma<-np_list[grep("PMA", np_list)]

Nonpareil.curve.batch(np_list_pma, plot.opts = list(legend = NA, 
                                                        plot.model = F, 
                                                        plot.diversity = F,
                                                        main = NA))
#dev.off()
np_list_npma<-np_list[!grepl("PMA", np_list)]

Nonpareil.curve.batch(np_list_npma, plot.opts = list(legend = NA, 
                                                        plot.model = F, 
                                                        plot.diversity = F,
                                                        main = NA))
#dev.off()

```


# Save NonPareil Summary
```{r}
## generate summary

np_summary <-as.data.frame(
                            summary(Nonpareil.curve.batch(np_list, plot = F))
                            )
#write_csv2(np_summary, "../../results/notebook_out/00_NonPareilSummary.csv")
np_summary
```

```{r}
## compute summary stats: mean, med, sd, se
mean(summary(Nonpareil.curve.batch(np_list, plot = F))[,2])
median(summary(Nonpareil.curve.batch(np_list, plot = F))[,2])
sd(summary(Nonpareil.curve.batch(np_list, plot = F))[,2])
sd(summary(Nonpareil.curve.batch(np_list, plot = F))[,2])/sqrt(np_length)

```
```{r}
np_summary %>%
  ggplot( aes(x=C)) +
    geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.8) 

np_summary %>%
  ggplot( aes(x=diversity, y=C)) +
    geom_point() 

np_summary %>% 
  as_tibble(rownames = "Samples") %>%
  separate(Samples, into=c("Sample", "Method")) %>%
  filter(!str_detect(Sample,"B20")) %>%
  mutate(Method2 = if_else(str_detect(Method, "DNase"), "DNase", 
                          if_else(str_detect(Method, "PMA"), "PMA", "Na"
                                  ))) %>%
  ggplot(aes(x=Method, y=C)) + 
  geom_violin(trim = F, aes(fill=Method2)) + 
  geom_boxplot(width=0.1) + stat_compare_means(paired = TRUE, ref.group = "NaNa", hide.ns	= T) 

tmp <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf), symbols = c("****", "***", "**", "*", "ns"))
```



```{r}
mgx <- read_csv("../../results/minimal_SCRIPT_01_Metagenomics.csv", name_repair = "universal")[1:11]

np.meta <- clusters %>% mutate(cluster_num = as.factor(cluster_num)) %>%
  left_join(shannon.cluster) %>%
  separate(name, into=c("pt", "tube"), sep = "-TUBE")

np.meta <- np.meta %>% left_join(mgx, by=c("tube" ="DNA.tube.ID" ))

np.mgx2amp<- np_summary %>% rownames_to_column() %>%
  left_join(np.meta, by=c("rowname"="Batch_sample")) %>% drop_na(tube)
#missing <- np.mgx2amp %>% filter(is.na(tube)) 
#mgx %>% filter(Batch_sample %in% missing$rowname)
ggplot(np.mgx2amp, aes(x=factor(cluster_num), y=C)) +
  geom_boxplot()


ggplot(np.mgx2amp, aes(x=value, y=C)) +
  geom_point() + 
  geom_smooth(method = "lm") +
  nature_theme("Diag", "value") + 
  theme(aspect.ratio=1) 

ggscatter(np.mgx2amp, x = "value", y = "diversity", #facet.by="success", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "AMP Value", ylab = "NonPareil Value", title = "")
```


